version: '3.8'

services:
  reportador:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: qasl-reportador
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      DB_HOST: qasl-nexus-db
    volumes:
      - ./reports:/app/reports
    networks:
      - qasl-network

networks:
  qasl-network:
    name: qasl-nexus-network
    external: true
